<?php $currentCategory =  Mage::registry('current_category');?>
<?php $currentProduct =  Mage::registry('current_product');?>
<?php if($currentCategory!='') {?>
	     <?php  $currentCatId = $currentCategory->getId();?> 
<?php }?>

<?php if($currentProduct!='') {
		$currentProductId = $currentProduct->getId();
	}?>
	

<?php if($currentProductId=='') { ?>
<?php $active= "category_active";?>
<?php } else {?>
<?php $activeProduct= "category_active";?>
<?php }?>

  
<?php 
		$productsCollecitonOne = Mage::getModel('catalog/category')->load(5)
							->getProductCollection()
							->addAttributeToSelect('*')
							->addAttributeToFilter('status', 1)
							->addAttributeToFilter('visibility', 4)
							 ->setOrder('name', 'ASC');
?>
  
<div class="remove-filter">
	<a href="javascript:void(0);"><i class="fa fa-close"></i></a>
</div>

<div class="block-title"> <span class="<?php if($currentCatId=='5') { echo $active ;}?>"><a href="<?php echo Mage::getBaseUrl()?>accessories.html">ALL ACCESSORIES</a></span> </div>
  <div class="left-category">
    <!--h3> <span class="<?php //if($currentCatId=='21') { echo $active ;}?>"><a href="<?php echo Mage::getBaseUrl()?>paper/correspondence-paper.html">Correspondence Paper</a></span></h3-->
    <ul>
       <?php 
   foreach($productsCollecitonOne as $productData) {  ?>
   <li><span class="<?php if($currentProductId==$productData->getId()) { echo $activeProduct ;}?>">
   		<a href="<?php echo $productData->getProductUrl()?>" class="tst"><?php echo $productData->getName()?>	</a>
            </span>
  </li>
<?php } ?>
    </ul>
  </div>