<?php
$is_persistent = Mage::helper('opc')->isPersistentMember(); 
?>
<p class="left"><a class="signin-modal opc-login-trigger <?php if($is_persistent):?>is_persistent<?php endif;?>" data-modal="modal-login"><?php echo $this->__('LOGIN')?></a></p>

<div class="md-modal md-effect-7" id="modal-login">
	<div class="md-content">
			<div class="md-modal-header">
				<button type="button" class="close"><i class="fa fa-close"></i></button>
				<h4><?php echo $this->__('Login to your Account')?></h4>
			</div>	
			<div id="thanksmsgresult"></div>
			<div class="md-content-wrapper">
				<form  method="post" id="login-form-popup">
		      		<?php echo $this->getBlockHtml('formkey'); ?>
			        <div>
		
						<ul class="form-list">
							<li>
								<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
								<div class="input-box">
									<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="emailtext" class="input-text" title="<?php echo $this->__('Email Address') ?>" />
								</div>
								<div class="clear"></div>
							</li>
							<div class="clear"></div>
							<li>
								<label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
								<div class="input-box">
									<input type="password" name="login[password]" class="input-text" id="passtext" title="<?php echo $this->__('Password') ?>" />
								</div>
								<div class="clear"></div>
							</li>
							<div class="clear"></div>
						</ul>				
					</div>
					<div class="clear"></div>
					<input name="context" type="hidden" value="checkout" />
					<button type="button" class="btn btn-primary" id="loginpopup"><span><span><?php echo $this->__('Login') ?></span></span></button>
					 
					 <span class="login-loader-popup" id="popuploaderimg"><img src="<?php echo $this->getSkinUrl('images/login-loader.gif')?>"></span>
				</form>
				<div class="forgotpassword-pop">
				   <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left forgotpassword"><?php echo $this->__('I forgot my password') ?></a>
                 </div>    
				<div class="clear"></div>
				<?php //echo $this->getChildhtml('forgotPassword');?>
				<div class="clear"></div>
			</div>
			
	</div>
</div>
<div class="md-overlay"></div>	
<script type="text/javascript">
    //<![CDATA[
        //var dataForm1 = new VarienForm('login-form', true);
    //]]>
</script>



<script type="text/javascript">



	function validation() {
		var email = jQuery('#emailtext').val();
		var pass = jQuery('#passtext').val();
		
		var i = 0;
		if (pass == '') {
		jQuery('#passtext').addClass('error');
		jQuery('#passtext').parent().append('<span class="errorvalidpass">Please enter a password</span>');
		jQuery('body .errorvalidpass:gt(0)').remove();


		i++;
		} else {
		jQuery('#passtext').removeClass('error');
		jQuery('#passtext').removeClass('errorvalidpass');
		}

		
		
		
		
		var email_regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;


    if (email == '') {
        jQuery('#emailtext').addClass('error');
        jQuery('#emailtext').parent().append('<span class="errorvalid">Please enter a email address</span>');
        jQuery('body .errorvalid:gt(0)').remove();
   
        i++;
    } else if (!email_regex.test(email)) {
        jQuery('#emailtext').addClass('error');
    
        jQuery('#emailtext').parent().append('<span class="errorvalid">Please enter a valid email address</span>');
         jQuery('body .errorvalid:gt(0)').remove();
        i++;
    }else{
		  jQuery('#emailtext').removeClass('error'); 
		   jQuery('#emailtext').removeClass('errorvalid');
		
		} 
		
		
		if(i==0) {
			
		  return true;
		} else {
		  return false;
		}
		
	}


  jQuery('#loginpopup').on('click',function(event){   
			
			var resultcheck  = validation();
			
	
			if(resultcheck == true) {
			jQuery('#popuploaderimg').show();	
			url = '<?php echo Mage::getBaseUrl()?>customer/account/loginPost/';
			var data = jQuery('#login-form-popup').serialize();
			data += '&isAjax=1';  
				jQuery('.login-loader').show(); 
				jQuery('.login-loader').css('display','block');
					try {
						jQuery.ajax({
							url: url,
							dataType: 'json',
							type : 'post',
							data: data,
							success: function(data){
								jQuery('.loader').hide();
								if(data.success == '1'){ 
									jQuery('#popuploaderimg').hide();	
									window.location.href="http://www.threecliveroad.com/index.php/onepage/?___SID=U";
								
									jQuery('#login-form-popup')[0].reset();
									
								}else{
									jQuery('#thanksmsgresult').empty().html(data.error);
									jQuery('#thanksmsgresult').css('color', 'red');
									jQuery('#popuploaderimg').hide();
								}
								
							}
						});
					} catch (e) {
						
					}	
					
					
				return false;
			}
		});
    
		//End of ajax code
    //]]>
    </script>
    
    <style>
		#popuploaderimg {
		display: none;
		}
		span.errorvalidpass {
		color: red;
		font-size: 10px;
		}
		
		.forgotpassword-pop {
		margin: 12px 0px 20px;
		}
    </style>
